### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by lu2sheng**
This change is [Reviewable](https://reviewable.io/reviews/mros/code_review_test/2)

### CODE REVIEW

**Comment by MROS** [comment]
___
*[README.md, line 5 at r1](https://reviewable.io/reviews/mros/code_review_test/2#-LkeL00P9ohiMlj7URho:-LkeL00Q7PaAdqY5-IVw:b-36dpu5) ([raw file](https://github.com/mros/code_review_test/blob/5d91844d9f9d8317efe7033e420221c9ebc282d7/README.md#L5)):*
> ```Markdown
> 我希望的 code review 工具應該擁有以下功能
> 
> - 可以指派審查者
> ```

github 內建就有這個功能

**Comment by MROS** [comment]
___
*[README.md, line 7 at r1](https://reviewable.io/reviews/mros/code_review_test/2#-LkeLE1mEhlTnO1YJP01:-LkeLE1mEhlTnO1YJP02:bdlay8z) ([raw file](https://github.com/mros/code_review_test/blob/5d91844d9f9d8317efe7033e420221c9ebc282d7/README.md#L7)):*
> ```Markdown
> - 可以指派審查者
> - 可以做行級別的評論
> - 完成評論後，會自動通知被審查者
> ```

這個 github 也會通知

**Review by MROS — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mros/code_review_test/2)* status: all files reviewed, 2 unresolved discussions (waiting on @lu2sheng)

**Review by lu2sheng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mros/code_review_test/2)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @MROS)

___
*[README.md, line 5 at r1](https://reviewable.io/reviews/mros/code_review_test/2#-LkeL00P9ohiMlj7URho:-LkeNYIp8zakoVXu3eI-:b-896fix) ([raw file](https://github.com/mros/code_review_test/blob/5d91844d9f9d8317efe7033e420221c9ebc282d7/README.md#L5)):*
<details><summary><i>Previously, MROS wrote…</i></summary><blockquote>

github 內建就有這個功能
</blockquote></details>

Done.
___
*[README.md, line 7 at r1](https://reviewable.io/reviews/mros/code_review_test/2#-LkeLE1mEhlTnO1YJP01:-LkeNZFo1r1Z0POVpQle:b-896fix) ([raw file](https://github.com/mros/code_review_test/blob/5d91844d9f9d8317efe7033e420221c9ebc282d7/README.md#L7)):*
<details><summary><i>Previously, MROS wrote…</i></summary><blockquote>

這個 github 也會通知
</blockquote></details>

Done.

**Review by MROS — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mros/code_review_test/2#-:-LkeNj4eBuDgZWn_O7h3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
